/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Nov 17 10:15:18 CET 2016
 */
package com.github.lburgazzoli.camel.salesforce.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Priority
 */
public enum Case_PriorityEnum {

    // High
    HIGH("High"),
    // Low
    LOW("Low"),
    // Medium
    MEDIUM("Medium");

    final String value;

    private Case_PriorityEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Case_PriorityEnum fromValue(String value) {
        for (Case_PriorityEnum e : Case_PriorityEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
