/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 23 10:44:07 CEST 2017
 */
package com.github.lburgazzoli.camel.salesforce.model;

import java.util.ArrayList;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject Case
 */
@XStreamAlias("Case")
public class Case extends AbstractDescribedSObjectBase {

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    // CaseNumber
    private String CaseNumber;

    @JsonProperty("CaseNumber")
    public String getCaseNumber() {
        return this.CaseNumber;
    }

    @JsonProperty("CaseNumber")
    public void setCaseNumber(String CaseNumber) {
        this.CaseNumber = CaseNumber;
    }

    // ContactId
    private String ContactId;

    @JsonProperty("ContactId")
    public String getContactId() {
        return this.ContactId;
    }

    @JsonProperty("ContactId")
    public void setContactId(String ContactId) {
        this.ContactId = ContactId;
    }

    // AccountId
    private String AccountId;

    @JsonProperty("AccountId")
    public String getAccountId() {
        return this.AccountId;
    }

    @JsonProperty("AccountId")
    public void setAccountId(String AccountId) {
        this.AccountId = AccountId;
    }

    // AssetId
    private String AssetId;

    @JsonProperty("AssetId")
    public String getAssetId() {
        return this.AssetId;
    }

    @JsonProperty("AssetId")
    public void setAssetId(String AssetId) {
        this.AssetId = AssetId;
    }

    // ParentId
    private String ParentId;

    @JsonProperty("ParentId")
    public String getParentId() {
        return this.ParentId;
    }

    @JsonProperty("ParentId")
    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

    // SuppliedName
    private String SuppliedName;

    @JsonProperty("SuppliedName")
    public String getSuppliedName() {
        return this.SuppliedName;
    }

    @JsonProperty("SuppliedName")
    public void setSuppliedName(String SuppliedName) {
        this.SuppliedName = SuppliedName;
    }

    // SuppliedEmail
    private String SuppliedEmail;

    @JsonProperty("SuppliedEmail")
    public String getSuppliedEmail() {
        return this.SuppliedEmail;
    }

    @JsonProperty("SuppliedEmail")
    public void setSuppliedEmail(String SuppliedEmail) {
        this.SuppliedEmail = SuppliedEmail;
    }

    // SuppliedPhone
    private String SuppliedPhone;

    @JsonProperty("SuppliedPhone")
    public String getSuppliedPhone() {
        return this.SuppliedPhone;
    }

    @JsonProperty("SuppliedPhone")
    public void setSuppliedPhone(String SuppliedPhone) {
        this.SuppliedPhone = SuppliedPhone;
    }

    // SuppliedCompany
    private String SuppliedCompany;

    @JsonProperty("SuppliedCompany")
    public String getSuppliedCompany() {
        return this.SuppliedCompany;
    }

    @JsonProperty("SuppliedCompany")
    public void setSuppliedCompany(String SuppliedCompany) {
        this.SuppliedCompany = SuppliedCompany;
    }

    // Type
    @XStreamConverter(PicklistEnumConverter.class)
    private TypeEnum Type;

    @JsonProperty("Type")
    public TypeEnum getType() {
        return this.Type;
    }

    @JsonProperty("Type")
    public void setType(TypeEnum Type) {
        this.Type = Type;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private StatusEnum Status;

    @JsonProperty("Status")
    public StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(StatusEnum Status) {
        this.Status = Status;
    }

    // Reason
    @XStreamConverter(PicklistEnumConverter.class)
    private ReasonEnum Reason;

    @JsonProperty("Reason")
    public ReasonEnum getReason() {
        return this.Reason;
    }

    @JsonProperty("Reason")
    public void setReason(ReasonEnum Reason) {
        this.Reason = Reason;
    }

    // Origin
    @XStreamConverter(PicklistEnumConverter.class)
    private OriginEnum Origin;

    @JsonProperty("Origin")
    public OriginEnum getOrigin() {
        return this.Origin;
    }

    @JsonProperty("Origin")
    public void setOrigin(OriginEnum Origin) {
        this.Origin = Origin;
    }

    // Subject
    private String Subject;

    @JsonProperty("Subject")
    public String getSubject() {
        return this.Subject;
    }

    @JsonProperty("Subject")
    public void setSubject(String Subject) {
        this.Subject = Subject;
    }

    // Priority
    @XStreamConverter(PicklistEnumConverter.class)
    private PriorityEnum Priority;

    @JsonProperty("Priority")
    public PriorityEnum getPriority() {
        return this.Priority;
    }

    @JsonProperty("Priority")
    public void setPriority(PriorityEnum Priority) {
        this.Priority = Priority;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // IsClosed
    private Boolean IsClosed;

    @JsonProperty("IsClosed")
    public Boolean getIsClosed() {
        return this.IsClosed;
    }

    @JsonProperty("IsClosed")
    public void setIsClosed(Boolean IsClosed) {
        this.IsClosed = IsClosed;
    }

    // ClosedDate
    private org.joda.time.DateTime ClosedDate;

    @JsonProperty("ClosedDate")
    public org.joda.time.DateTime getClosedDate() {
        return this.ClosedDate;
    }

    @JsonProperty("ClosedDate")
    public void setClosedDate(org.joda.time.DateTime ClosedDate) {
        this.ClosedDate = ClosedDate;
    }

    // IsEscalated
    private Boolean IsEscalated;

    @JsonProperty("IsEscalated")
    public Boolean getIsEscalated() {
        return this.IsEscalated;
    }

    @JsonProperty("IsEscalated")
    public void setIsEscalated(Boolean IsEscalated) {
        this.IsEscalated = IsEscalated;
    }

    // ContactPhone
    private String ContactPhone;

    @JsonProperty("ContactPhone")
    public String getContactPhone() {
        return this.ContactPhone;
    }

    @JsonProperty("ContactPhone")
    public void setContactPhone(String ContactPhone) {
        this.ContactPhone = ContactPhone;
    }

    // ContactMobile
    private String ContactMobile;

    @JsonProperty("ContactMobile")
    public String getContactMobile() {
        return this.ContactMobile;
    }

    @JsonProperty("ContactMobile")
    public void setContactMobile(String ContactMobile) {
        this.ContactMobile = ContactMobile;
    }

    // ContactEmail
    private String ContactEmail;

    @JsonProperty("ContactEmail")
    public String getContactEmail() {
        return this.ContactEmail;
    }

    @JsonProperty("ContactEmail")
    public void setContactEmail(String ContactEmail) {
        this.ContactEmail = ContactEmail;
    }

    // ContactFax
    private String ContactFax;

    @JsonProperty("ContactFax")
    public String getContactFax() {
        return this.ContactFax;
    }

    @JsonProperty("ContactFax")
    public void setContactFax(String ContactFax) {
        this.ContactFax = ContactFax;
    }

    // EngineeringReqNumber__c
    private String EngineeringReqNumber__c;

    @JsonProperty("EngineeringReqNumber__c")
    public String getEngineeringReqNumber__c() {
        return this.EngineeringReqNumber__c;
    }

    @JsonProperty("EngineeringReqNumber__c")
    public void setEngineeringReqNumber__c(String EngineeringReqNumber__c) {
        this.EngineeringReqNumber__c = EngineeringReqNumber__c;
    }

    // SLAViolation__c
    @XStreamConverter(PicklistEnumConverter.class)
    private SLAViolationEnum SLAViolation__c;

    @JsonProperty("SLAViolation__c")
    public SLAViolationEnum getSLAViolation__c() {
        return this.SLAViolation__c;
    }

    @JsonProperty("SLAViolation__c")
    public void setSLAViolation__c(SLAViolationEnum SLAViolation__c) {
        this.SLAViolation__c = SLAViolation__c;
    }

    // Product__c
    @XStreamConverter(PicklistEnumConverter.class)
    private ProductEnum Product__c;

    @JsonProperty("Product__c")
    public ProductEnum getProduct__c() {
        return this.Product__c;
    }

    @JsonProperty("Product__c")
    public void setProduct__c(ProductEnum Product__c) {
        this.Product__c = Product__c;
    }

    // PotentialLiability__c
    @XStreamConverter(PicklistEnumConverter.class)
    private PotentialLiabilityEnum PotentialLiability__c;

    @JsonProperty("PotentialLiability__c")
    public PotentialLiabilityEnum getPotentialLiability__c() {
        return this.PotentialLiability__c;
    }

    @JsonProperty("PotentialLiability__c")
    public void setPotentialLiability__c(PotentialLiabilityEnum PotentialLiability__c) {
        this.PotentialLiability__c = PotentialLiability__c;
    }

    // ExtenralID__c
    private String ExtenralID__c;

    @JsonProperty("ExtenralID__c")
    public String getExtenralID__c() {
        return this.ExtenralID__c;
    }

    @JsonProperty("ExtenralID__c")
    public void setExtenralID__c(String ExtenralID__c) {
        this.ExtenralID__c = ExtenralID__c;
    }

    // InternalID__c
    private String InternalID__c;

    @JsonProperty("InternalID__c")
    public String getInternalID__c() {
        return this.InternalID__c;
    }

    @JsonProperty("InternalID__c")
    public void setInternalID__c(String InternalID__c) {
        this.InternalID__c = InternalID__c;
    }


    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();
//wtf

        description.setMergeable(false);
        description.setCreateable(true);
        description.setQueryable(true);
        description.setLabel("Case");

        final List<RecordTypeInfo> recordTypeInfos1 = new ArrayList<>();
        description.setRecordTypeInfos(recordTypeInfos1);

        final RecordTypeInfo recordTypeInfo1 = new RecordTypeInfo();
        recordTypeInfos1.add(recordTypeInfo1);

        recordTypeInfo1.setDefaultRecordTypeMapping(true);
        recordTypeInfo1.setRecordTypeId("012000000000000AAA");
        recordTypeInfo1.setAvailable(true);

        final InfoUrls infoUrls1 = new InfoUrls();
        infoUrls1.setLayout("/services/data/v39.0/sobjects/Case/describe/layouts/012000000000000AAA");
        recordTypeInfo1.setUrls(infoUrls1);
        recordTypeInfo1.setName("Master");


        description.setReplicateable(true);
        description.setName("Case");
        description.setLayoutable(true);
        description.setDeprecatedAndHidden(false);
        description.setMruEnabled(true);
        description.setFeedEnabled(true);
        description.setSearchable(true);
        description.setCustomSetting(false);
        description.setRetrieveable(true);
        description.setKeyPrefix("500");
        description.setUndeletable(true);
        description.setSearchLayoutable("true");
        description.setCustom(false);
        description.setTriggerable(true);

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setDescribe("/services/data/v39.0/sobjects/Case/describe");
        sObjectDescriptionUrls1.setCaseArticleSuggestions("/services/data/v39.0/sobjects/Case/suggestedArticles");
        sObjectDescriptionUrls1.setCaseRowArticleSuggestions("/services/data/v39.0/sobjects/Case/{ID}/suggestedArticles");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v39.0/sobjects/Case/{ID}");
        sObjectDescriptionUrls1.setListviews("/services/data/v39.0/sobjects/Case/listviews");
        sObjectDescriptionUrls1.setUiNewRecord("https://eu11.salesforce.com/500/e");
        sObjectDescriptionUrls1.setLayouts("/services/data/v39.0/sobjects/Case/describe/layouts");
        sObjectDescriptionUrls1.setQuickActions("/services/data/v39.0/sobjects/Case/quickActions");
        sObjectDescriptionUrls1.setUiEditTemplate("https://eu11.salesforce.com/{ID}/e");
        sObjectDescriptionUrls1.setSobject("/services/data/v39.0/sobjects/Case");
        sObjectDescriptionUrls1.setDefaultValues("/services/data/v39.0/sobjects/Case/defaultValues?recordTypeId&fields");
        sObjectDescriptionUrls1.setCompactLayouts("/services/data/v39.0/sobjects/Case/describe/compactLayouts");
        sObjectDescriptionUrls1.setApprovalLayouts("/services/data/v39.0/sobjects/Case/describe/approvalLayouts");
        sObjectDescriptionUrls1.setUiDetailTemplate("https://eu11.salesforce.com/{ID}");
        description.setUrls(sObjectDescriptionUrls1);
        description.setCompactLayoutable(true);

        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = new SObjectField();
        fields1.add(sObjectField1);

        sObjectField1.setWriteRequiresMasterRead(false);
        sObjectField1.setNillable(false);
        sObjectField1.setCreateable(false);
        sObjectField1.setEncrypted(false);
        sObjectField1.setDependentPicklist(false);
        sObjectField1.setDigits("0");
        sObjectField1.setLabel("Case ID");
        sObjectField1.setHighScaleNumber(false);
        sObjectField1.setDisplayLocationInDecimal(false);
        sObjectField1.setName("Id");
        sObjectField1.setHtmlFormatted(false);
        sObjectField1.setDeprecatedAndHidden(false);
        sObjectField1.setRestrictedPicklist(false);
        sObjectField1.setNameField(false);
        sObjectField1.setCaseSensitive(false);
        sObjectField1.setPermissionable(false);
        sObjectField1.setCascadeDelete(false);
        sObjectField1.setDefaultedOnCreate(true);
        sObjectField1.setExternalId(false);
        sObjectField1.setSoapType("tns:ID");
        sObjectField1.setScale(0);
        sObjectField1.setCustom(false);
        sObjectField1.setGroupable(true);
        sObjectField1.setRestrictedDelete(false);
        sObjectField1.setCalculated(false);
        sObjectField1.setNamePointing(false);
        sObjectField1.setIdLookup(true);
        sObjectField1.setType("id");
        sObjectField1.setPrecision(0);
        sObjectField1.setLength(18);
        sObjectField1.setSortable(true);
        sObjectField1.setByteLength(18);
        sObjectField1.setUpdateable(false);
        sObjectField1.setFilterable(true);
        sObjectField1.setQueryByDistance(false);
        sObjectField1.setUnique(false);
        sObjectField1.setAutoNumber(false);

        final SObjectField sObjectField2 = new SObjectField();
        fields1.add(sObjectField2);

        sObjectField2.setWriteRequiresMasterRead(false);
        sObjectField2.setNillable(false);
        sObjectField2.setCreateable(false);
        sObjectField2.setEncrypted(false);
        sObjectField2.setDependentPicklist(false);
        sObjectField2.setDigits("0");
        sObjectField2.setLabel("Deleted");
        sObjectField2.setHighScaleNumber(false);
        sObjectField2.setDisplayLocationInDecimal(false);
        sObjectField2.setName("IsDeleted");
        sObjectField2.setHtmlFormatted(false);
        sObjectField2.setDeprecatedAndHidden(false);
        sObjectField2.setDefaultValue("false");
        sObjectField2.setRestrictedPicklist(false);
        sObjectField2.setNameField(false);
        sObjectField2.setCaseSensitive(false);
        sObjectField2.setPermissionable(false);
        sObjectField2.setCascadeDelete(false);
        sObjectField2.setDefaultedOnCreate(true);
        sObjectField2.setExternalId(false);
        sObjectField2.setSoapType("xsd:boolean");
        sObjectField2.setScale(0);
        sObjectField2.setCustom(false);
        sObjectField2.setGroupable(true);
        sObjectField2.setRestrictedDelete(false);
        sObjectField2.setCalculated(false);
        sObjectField2.setNamePointing(false);
        sObjectField2.setIdLookup(false);
        sObjectField2.setType("boolean");
        sObjectField2.setPrecision(0);
        sObjectField2.setLength(0);
        sObjectField2.setSortable(true);
        sObjectField2.setByteLength(0);
        sObjectField2.setUpdateable(false);
        sObjectField2.setFilterable(true);
        sObjectField2.setQueryByDistance(false);
        sObjectField2.setUnique(false);
        sObjectField2.setAutoNumber(false);

        final SObjectField sObjectField3 = new SObjectField();
        fields1.add(sObjectField3);

        sObjectField3.setWriteRequiresMasterRead(false);
        sObjectField3.setNillable(false);
        sObjectField3.setCreateable(false);
        sObjectField3.setEncrypted(false);
        sObjectField3.setDependentPicklist(false);
        sObjectField3.setDigits("0");
        sObjectField3.setLabel("Case Number");
        sObjectField3.setHighScaleNumber(false);
        sObjectField3.setDisplayLocationInDecimal(false);
        sObjectField3.setName("CaseNumber");
        sObjectField3.setHtmlFormatted(false);
        sObjectField3.setDeprecatedAndHidden(false);
        sObjectField3.setRestrictedPicklist(false);
        sObjectField3.setNameField(true);
        sObjectField3.setCaseSensitive(false);
        sObjectField3.setPermissionable(false);
        sObjectField3.setCascadeDelete(false);
        sObjectField3.setDefaultedOnCreate(true);
        sObjectField3.setExternalId(false);
        sObjectField3.setSoapType("xsd:string");
        sObjectField3.setScale(0);
        sObjectField3.setCustom(false);
        sObjectField3.setGroupable(false);
        sObjectField3.setRestrictedDelete(false);
        sObjectField3.setCalculated(false);
        sObjectField3.setNamePointing(false);
        sObjectField3.setIdLookup(true);
        sObjectField3.setType("string");
        sObjectField3.setPrecision(0);
        sObjectField3.setLength(30);
        sObjectField3.setSortable(true);
        sObjectField3.setByteLength(90);
        sObjectField3.setUpdateable(false);
        sObjectField3.setFilterable(true);
        sObjectField3.setQueryByDistance(false);
        sObjectField3.setUnique(false);
        sObjectField3.setAutoNumber(true);

        final SObjectField sObjectField4 = new SObjectField();
        fields1.add(sObjectField4);

        sObjectField4.setWriteRequiresMasterRead(false);
        sObjectField4.setNillable(true);
        sObjectField4.setCreateable(true);
        sObjectField4.setEncrypted(false);
        sObjectField4.setDependentPicklist(false);
        sObjectField4.setDigits("0");
        sObjectField4.setLabel("Contact ID");
        sObjectField4.setHighScaleNumber(false);
        sObjectField4.setDisplayLocationInDecimal(false);
        sObjectField4.setName("ContactId");
        sObjectField4.setHtmlFormatted(false);
        sObjectField4.setDeprecatedAndHidden(false);
        sObjectField4.setRestrictedPicklist(false);
        sObjectField4.setNameField(false);
        sObjectField4.setCaseSensitive(false);
        sObjectField4.setPermissionable(true);
        sObjectField4.setCascadeDelete(false);
        sObjectField4.setDefaultedOnCreate(false);
        sObjectField4.setExternalId(false);
        sObjectField4.setSoapType("tns:ID");
        sObjectField4.setScale(0);
        sObjectField4.setCustom(false);
        sObjectField4.setGroupable(true);
        sObjectField4.setRestrictedDelete(false);
        sObjectField4.setCalculated(false);
        sObjectField4.setNamePointing(false);
        sObjectField4.setIdLookup(false);
        sObjectField4.setType("reference");
        sObjectField4.setRelationshipName("Contact");

        final List<String> referenceTo1 = new ArrayList<>();
        sObjectField4.setReferenceTo(referenceTo1);

        referenceTo1.add("Contact");

        sObjectField4.setPrecision(0);
        sObjectField4.setLength(18);
        sObjectField4.setSortable(true);
        sObjectField4.setByteLength(18);
        sObjectField4.setUpdateable(true);
        sObjectField4.setFilterable(true);
        sObjectField4.setQueryByDistance(false);
        sObjectField4.setUnique(false);
        sObjectField4.setAutoNumber(false);

        final SObjectField sObjectField5 = new SObjectField();
        fields1.add(sObjectField5);

        sObjectField5.setWriteRequiresMasterRead(false);
        sObjectField5.setNillable(true);
        sObjectField5.setCreateable(true);
        sObjectField5.setEncrypted(false);
        sObjectField5.setDependentPicklist(false);
        sObjectField5.setDigits("0");
        sObjectField5.setLabel("Account ID");
        sObjectField5.setHighScaleNumber(false);
        sObjectField5.setDisplayLocationInDecimal(false);
        sObjectField5.setName("AccountId");
        sObjectField5.setHtmlFormatted(false);
        sObjectField5.setDeprecatedAndHidden(false);
        sObjectField5.setRestrictedPicklist(false);
        sObjectField5.setNameField(false);
        sObjectField5.setCaseSensitive(false);
        sObjectField5.setPermissionable(true);
        sObjectField5.setCascadeDelete(false);
        sObjectField5.setDefaultedOnCreate(false);
        sObjectField5.setExternalId(false);
        sObjectField5.setSoapType("tns:ID");
        sObjectField5.setScale(0);
        sObjectField5.setCustom(false);
        sObjectField5.setGroupable(true);
        sObjectField5.setRestrictedDelete(false);
        sObjectField5.setCalculated(false);
        sObjectField5.setNamePointing(false);
        sObjectField5.setIdLookup(false);
        sObjectField5.setType("reference");
        sObjectField5.setRelationshipName("Account");

        final List<String> referenceTo2 = new ArrayList<>();
        sObjectField5.setReferenceTo(referenceTo2);

        referenceTo2.add("Account");

        sObjectField5.setPrecision(0);
        sObjectField5.setLength(18);
        sObjectField5.setSortable(true);
        sObjectField5.setByteLength(18);
        sObjectField5.setUpdateable(true);
        sObjectField5.setFilterable(true);
        sObjectField5.setQueryByDistance(false);
        sObjectField5.setUnique(false);
        sObjectField5.setAutoNumber(false);

        final SObjectField sObjectField6 = new SObjectField();
        fields1.add(sObjectField6);

        sObjectField6.setWriteRequiresMasterRead(false);
        sObjectField6.setNillable(true);
        sObjectField6.setCreateable(true);
        sObjectField6.setEncrypted(false);
        sObjectField6.setDependentPicklist(false);
        sObjectField6.setDigits("0");
        sObjectField6.setLabel("Asset ID");
        sObjectField6.setHighScaleNumber(false);
        sObjectField6.setDisplayLocationInDecimal(false);
        sObjectField6.setName("AssetId");
        sObjectField6.setHtmlFormatted(false);
        sObjectField6.setDeprecatedAndHidden(false);
        sObjectField6.setRestrictedPicklist(false);
        sObjectField6.setNameField(false);
        sObjectField6.setCaseSensitive(false);
        sObjectField6.setPermissionable(true);
        sObjectField6.setCascadeDelete(false);
        sObjectField6.setDefaultedOnCreate(false);
        sObjectField6.setExternalId(false);
        sObjectField6.setSoapType("tns:ID");
        sObjectField6.setScale(0);
        sObjectField6.setCustom(false);
        sObjectField6.setGroupable(true);
        sObjectField6.setRestrictedDelete(false);
        sObjectField6.setCalculated(false);
        sObjectField6.setNamePointing(false);
        sObjectField6.setIdLookup(false);
        sObjectField6.setType("reference");
        sObjectField6.setRelationshipName("Asset");

        final List<String> referenceTo3 = new ArrayList<>();
        sObjectField6.setReferenceTo(referenceTo3);

        referenceTo3.add("Asset");

        sObjectField6.setPrecision(0);
        sObjectField6.setLength(18);
        sObjectField6.setSortable(true);
        sObjectField6.setByteLength(18);
        sObjectField6.setUpdateable(true);
        sObjectField6.setFilterable(true);
        sObjectField6.setQueryByDistance(false);
        sObjectField6.setUnique(false);
        sObjectField6.setAutoNumber(false);

        final SObjectField sObjectField7 = new SObjectField();
        fields1.add(sObjectField7);

        sObjectField7.setWriteRequiresMasterRead(false);
        sObjectField7.setNillable(true);
        sObjectField7.setCreateable(true);
        sObjectField7.setEncrypted(false);
        sObjectField7.setDependentPicklist(false);
        sObjectField7.setDigits("0");
        sObjectField7.setLabel("Parent Case ID");
        sObjectField7.setHighScaleNumber(false);
        sObjectField7.setDisplayLocationInDecimal(false);
        sObjectField7.setName("ParentId");
        sObjectField7.setHtmlFormatted(false);
        sObjectField7.setDeprecatedAndHidden(false);
        sObjectField7.setRestrictedPicklist(false);
        sObjectField7.setNameField(false);
        sObjectField7.setCaseSensitive(false);
        sObjectField7.setPermissionable(true);
        sObjectField7.setCascadeDelete(false);
        sObjectField7.setDefaultedOnCreate(false);
        sObjectField7.setExternalId(false);
        sObjectField7.setSoapType("tns:ID");
        sObjectField7.setScale(0);
        sObjectField7.setCustom(false);
        sObjectField7.setGroupable(true);
        sObjectField7.setRestrictedDelete(false);
        sObjectField7.setCalculated(false);
        sObjectField7.setNamePointing(false);
        sObjectField7.setIdLookup(false);
        sObjectField7.setType("reference");
        sObjectField7.setRelationshipName("Parent");

        final List<String> referenceTo4 = new ArrayList<>();
        sObjectField7.setReferenceTo(referenceTo4);

        referenceTo4.add("Case");

        sObjectField7.setPrecision(0);
        sObjectField7.setLength(18);
        sObjectField7.setSortable(true);
        sObjectField7.setByteLength(18);
        sObjectField7.setUpdateable(true);
        sObjectField7.setFilterable(true);
        sObjectField7.setQueryByDistance(false);
        sObjectField7.setUnique(false);
        sObjectField7.setAutoNumber(false);

        final SObjectField sObjectField8 = new SObjectField();
        fields1.add(sObjectField8);

        sObjectField8.setWriteRequiresMasterRead(false);
        sObjectField8.setNillable(true);
        sObjectField8.setCreateable(true);
        sObjectField8.setEncrypted(false);
        sObjectField8.setDependentPicklist(false);
        sObjectField8.setDigits("0");
        sObjectField8.setLabel("Name");
        sObjectField8.setHighScaleNumber(false);
        sObjectField8.setDisplayLocationInDecimal(false);
        sObjectField8.setName("SuppliedName");
        sObjectField8.setHtmlFormatted(false);
        sObjectField8.setDeprecatedAndHidden(false);
        sObjectField8.setRestrictedPicklist(false);
        sObjectField8.setNameField(false);
        sObjectField8.setCaseSensitive(false);
        sObjectField8.setPermissionable(true);
        sObjectField8.setCascadeDelete(false);
        sObjectField8.setDefaultedOnCreate(false);
        sObjectField8.setExternalId(false);
        sObjectField8.setSoapType("xsd:string");
        sObjectField8.setScale(0);
        sObjectField8.setCustom(false);
        sObjectField8.setGroupable(true);
        sObjectField8.setRestrictedDelete(false);
        sObjectField8.setCalculated(false);
        sObjectField8.setNamePointing(false);
        sObjectField8.setIdLookup(false);
        sObjectField8.setType("string");
        sObjectField8.setPrecision(0);
        sObjectField8.setLength(80);
        sObjectField8.setSortable(true);
        sObjectField8.setByteLength(240);
        sObjectField8.setUpdateable(true);
        sObjectField8.setFilterable(true);
        sObjectField8.setQueryByDistance(false);
        sObjectField8.setUnique(false);
        sObjectField8.setAutoNumber(false);

        final SObjectField sObjectField9 = new SObjectField();
        fields1.add(sObjectField9);

        sObjectField9.setWriteRequiresMasterRead(false);
        sObjectField9.setNillable(true);
        sObjectField9.setCreateable(true);
        sObjectField9.setEncrypted(false);
        sObjectField9.setDependentPicklist(false);
        sObjectField9.setDigits("0");
        sObjectField9.setLabel("Email Address");
        sObjectField9.setHighScaleNumber(false);
        sObjectField9.setDisplayLocationInDecimal(false);
        sObjectField9.setName("SuppliedEmail");
        sObjectField9.setHtmlFormatted(false);
        sObjectField9.setDeprecatedAndHidden(false);
        sObjectField9.setRestrictedPicklist(false);
        sObjectField9.setNameField(false);
        sObjectField9.setCaseSensitive(false);
        sObjectField9.setPermissionable(true);
        sObjectField9.setCascadeDelete(false);
        sObjectField9.setDefaultedOnCreate(false);
        sObjectField9.setExternalId(false);
        sObjectField9.setSoapType("xsd:string");
        sObjectField9.setScale(0);
        sObjectField9.setCustom(false);
        sObjectField9.setGroupable(true);
        sObjectField9.setRestrictedDelete(false);
        sObjectField9.setCalculated(false);
        sObjectField9.setNamePointing(false);
        sObjectField9.setIdLookup(false);
        sObjectField9.setType("email");
        sObjectField9.setPrecision(0);
        sObjectField9.setLength(80);
        sObjectField9.setSortable(true);
        sObjectField9.setByteLength(240);
        sObjectField9.setUpdateable(true);
        sObjectField9.setFilterable(true);
        sObjectField9.setQueryByDistance(false);
        sObjectField9.setUnique(false);
        sObjectField9.setAutoNumber(false);

        final SObjectField sObjectField10 = new SObjectField();
        fields1.add(sObjectField10);

        sObjectField10.setWriteRequiresMasterRead(false);
        sObjectField10.setNillable(true);
        sObjectField10.setCreateable(true);
        sObjectField10.setEncrypted(false);
        sObjectField10.setDependentPicklist(false);
        sObjectField10.setDigits("0");
        sObjectField10.setLabel("Phone");
        sObjectField10.setHighScaleNumber(false);
        sObjectField10.setDisplayLocationInDecimal(false);
        sObjectField10.setName("SuppliedPhone");
        sObjectField10.setHtmlFormatted(false);
        sObjectField10.setDeprecatedAndHidden(false);
        sObjectField10.setRestrictedPicklist(false);
        sObjectField10.setNameField(false);
        sObjectField10.setCaseSensitive(false);
        sObjectField10.setPermissionable(true);
        sObjectField10.setCascadeDelete(false);
        sObjectField10.setDefaultedOnCreate(false);
        sObjectField10.setExternalId(false);
        sObjectField10.setSoapType("xsd:string");
        sObjectField10.setScale(0);
        sObjectField10.setCustom(false);
        sObjectField10.setGroupable(true);
        sObjectField10.setRestrictedDelete(false);
        sObjectField10.setCalculated(false);
        sObjectField10.setNamePointing(false);
        sObjectField10.setIdLookup(false);
        sObjectField10.setType("string");
        sObjectField10.setPrecision(0);
        sObjectField10.setLength(40);
        sObjectField10.setSortable(true);
        sObjectField10.setByteLength(120);
        sObjectField10.setUpdateable(true);
        sObjectField10.setFilterable(true);
        sObjectField10.setQueryByDistance(false);
        sObjectField10.setUnique(false);
        sObjectField10.setAutoNumber(false);

        final SObjectField sObjectField11 = new SObjectField();
        fields1.add(sObjectField11);

        sObjectField11.setWriteRequiresMasterRead(false);
        sObjectField11.setNillable(true);
        sObjectField11.setCreateable(true);
        sObjectField11.setEncrypted(false);
        sObjectField11.setDependentPicklist(false);
        sObjectField11.setDigits("0");
        sObjectField11.setLabel("Company");
        sObjectField11.setHighScaleNumber(false);
        sObjectField11.setDisplayLocationInDecimal(false);
        sObjectField11.setName("SuppliedCompany");
        sObjectField11.setHtmlFormatted(false);
        sObjectField11.setDeprecatedAndHidden(false);
        sObjectField11.setRestrictedPicklist(false);
        sObjectField11.setNameField(false);
        sObjectField11.setCaseSensitive(false);
        sObjectField11.setPermissionable(true);
        sObjectField11.setCascadeDelete(false);
        sObjectField11.setDefaultedOnCreate(false);
        sObjectField11.setExternalId(false);
        sObjectField11.setSoapType("xsd:string");
        sObjectField11.setScale(0);
        sObjectField11.setCustom(false);
        sObjectField11.setGroupable(true);
        sObjectField11.setRestrictedDelete(false);
        sObjectField11.setCalculated(false);
        sObjectField11.setNamePointing(false);
        sObjectField11.setIdLookup(false);
        sObjectField11.setType("string");
        sObjectField11.setPrecision(0);
        sObjectField11.setLength(80);
        sObjectField11.setSortable(true);
        sObjectField11.setByteLength(240);
        sObjectField11.setUpdateable(true);
        sObjectField11.setFilterable(true);
        sObjectField11.setQueryByDistance(false);
        sObjectField11.setUnique(false);
        sObjectField11.setAutoNumber(false);

        final SObjectField sObjectField12 = new SObjectField();
        fields1.add(sObjectField12);

        sObjectField12.setWriteRequiresMasterRead(false);
        sObjectField12.setNillable(true);
        sObjectField12.setCreateable(true);
        sObjectField12.setEncrypted(false);
        sObjectField12.setDependentPicklist(false);
        sObjectField12.setDigits("0");
        sObjectField12.setLabel("Case Type");
        sObjectField12.setHighScaleNumber(false);
        sObjectField12.setDisplayLocationInDecimal(false);
        sObjectField12.setName("Type");
        sObjectField12.setHtmlFormatted(false);
        sObjectField12.setDeprecatedAndHidden(false);
        sObjectField12.setRestrictedPicklist(false);
        sObjectField12.setNameField(false);
        sObjectField12.setCaseSensitive(false);
        sObjectField12.setPermissionable(true);
        sObjectField12.setCascadeDelete(false);
        sObjectField12.setDefaultedOnCreate(false);
        sObjectField12.setExternalId(false);
        sObjectField12.setSoapType("xsd:string");
        sObjectField12.setScale(0);
        sObjectField12.setCustom(false);
        sObjectField12.setGroupable(true);
        sObjectField12.setRestrictedDelete(false);
        sObjectField12.setCalculated(false);
        sObjectField12.setNamePointing(false);
        sObjectField12.setIdLookup(false);
        sObjectField12.setType("picklist");
        sObjectField12.setPrecision(0);
        sObjectField12.setLength(40);
        sObjectField12.setSortable(true);
        sObjectField12.setByteLength(120);
        sObjectField12.setUpdateable(true);
        sObjectField12.setFilterable(true);
        sObjectField12.setQueryByDistance(false);
        sObjectField12.setUnique(false);
        sObjectField12.setAutoNumber(false);

        final SObjectField sObjectField13 = new SObjectField();
        fields1.add(sObjectField13);

        sObjectField13.setWriteRequiresMasterRead(false);
        sObjectField13.setNillable(true);
        sObjectField13.setCreateable(true);
        sObjectField13.setEncrypted(false);
        sObjectField13.setDependentPicklist(false);
        sObjectField13.setDigits("0");
        sObjectField13.setLabel("Status");
        sObjectField13.setHighScaleNumber(false);
        sObjectField13.setDisplayLocationInDecimal(false);
        sObjectField13.setName("Status");
        sObjectField13.setHtmlFormatted(false);
        sObjectField13.setDeprecatedAndHidden(false);
        sObjectField13.setDefaultValue("New");
        sObjectField13.setRestrictedPicklist(false);
        sObjectField13.setNameField(false);
        sObjectField13.setCaseSensitive(false);
        sObjectField13.setPermissionable(false);
        sObjectField13.setCascadeDelete(false);
        sObjectField13.setDefaultedOnCreate(true);
        sObjectField13.setExternalId(false);
        sObjectField13.setSoapType("xsd:string");
        sObjectField13.setScale(0);
        sObjectField13.setCustom(false);
        sObjectField13.setGroupable(true);
        sObjectField13.setRestrictedDelete(false);
        sObjectField13.setCalculated(false);
        sObjectField13.setNamePointing(false);
        sObjectField13.setIdLookup(false);
        sObjectField13.setType("picklist");
        sObjectField13.setPrecision(0);
        sObjectField13.setLength(40);
        sObjectField13.setSortable(true);
        sObjectField13.setByteLength(120);
        sObjectField13.setUpdateable(true);
        sObjectField13.setFilterable(true);
        sObjectField13.setQueryByDistance(false);
        sObjectField13.setUnique(false);
        sObjectField13.setAutoNumber(false);

        final SObjectField sObjectField14 = new SObjectField();
        fields1.add(sObjectField14);

        sObjectField14.setWriteRequiresMasterRead(false);
        sObjectField14.setNillable(true);
        sObjectField14.setCreateable(true);
        sObjectField14.setEncrypted(false);
        sObjectField14.setDependentPicklist(false);
        sObjectField14.setDigits("0");
        sObjectField14.setLabel("Case Reason");
        sObjectField14.setHighScaleNumber(false);
        sObjectField14.setDisplayLocationInDecimal(false);
        sObjectField14.setName("Reason");
        sObjectField14.setHtmlFormatted(false);
        sObjectField14.setDeprecatedAndHidden(false);
        sObjectField14.setRestrictedPicklist(false);
        sObjectField14.setNameField(false);
        sObjectField14.setCaseSensitive(false);
        sObjectField14.setPermissionable(true);
        sObjectField14.setCascadeDelete(false);
        sObjectField14.setDefaultedOnCreate(false);
        sObjectField14.setExternalId(false);
        sObjectField14.setSoapType("xsd:string");
        sObjectField14.setScale(0);
        sObjectField14.setCustom(false);
        sObjectField14.setGroupable(true);
        sObjectField14.setRestrictedDelete(false);
        sObjectField14.setCalculated(false);
        sObjectField14.setNamePointing(false);
        sObjectField14.setIdLookup(false);
        sObjectField14.setType("picklist");
        sObjectField14.setPrecision(0);
        sObjectField14.setLength(40);
        sObjectField14.setSortable(true);
        sObjectField14.setByteLength(120);
        sObjectField14.setUpdateable(true);
        sObjectField14.setFilterable(true);
        sObjectField14.setQueryByDistance(false);
        sObjectField14.setUnique(false);
        sObjectField14.setAutoNumber(false);

        final SObjectField sObjectField15 = new SObjectField();
        fields1.add(sObjectField15);

        sObjectField15.setWriteRequiresMasterRead(false);
        sObjectField15.setNillable(true);
        sObjectField15.setCreateable(true);
        sObjectField15.setEncrypted(false);
        sObjectField15.setDependentPicklist(false);
        sObjectField15.setDigits("0");
        sObjectField15.setLabel("Case Origin");
        sObjectField15.setHighScaleNumber(false);
        sObjectField15.setDisplayLocationInDecimal(false);
        sObjectField15.setName("Origin");
        sObjectField15.setHtmlFormatted(false);
        sObjectField15.setDeprecatedAndHidden(false);
        sObjectField15.setRestrictedPicklist(false);
        sObjectField15.setNameField(false);
        sObjectField15.setCaseSensitive(false);
        sObjectField15.setPermissionable(true);
        sObjectField15.setCascadeDelete(false);
        sObjectField15.setDefaultedOnCreate(false);
        sObjectField15.setExternalId(false);
        sObjectField15.setSoapType("xsd:string");
        sObjectField15.setScale(0);
        sObjectField15.setCustom(false);
        sObjectField15.setGroupable(true);
        sObjectField15.setRestrictedDelete(false);
        sObjectField15.setCalculated(false);
        sObjectField15.setNamePointing(false);
        sObjectField15.setIdLookup(false);
        sObjectField15.setType("picklist");
        sObjectField15.setPrecision(0);
        sObjectField15.setLength(40);
        sObjectField15.setSortable(true);
        sObjectField15.setByteLength(120);
        sObjectField15.setUpdateable(true);
        sObjectField15.setFilterable(true);
        sObjectField15.setQueryByDistance(false);
        sObjectField15.setUnique(false);
        sObjectField15.setAutoNumber(false);

        final SObjectField sObjectField16 = new SObjectField();
        fields1.add(sObjectField16);

        sObjectField16.setWriteRequiresMasterRead(false);
        sObjectField16.setNillable(true);
        sObjectField16.setCreateable(true);
        sObjectField16.setEncrypted(false);
        sObjectField16.setDependentPicklist(false);
        sObjectField16.setDigits("0");
        sObjectField16.setLabel("Subject");
        sObjectField16.setHighScaleNumber(false);
        sObjectField16.setDisplayLocationInDecimal(false);
        sObjectField16.setName("Subject");
        sObjectField16.setHtmlFormatted(false);
        sObjectField16.setDeprecatedAndHidden(false);
        sObjectField16.setRestrictedPicklist(false);
        sObjectField16.setNameField(false);
        sObjectField16.setCaseSensitive(false);
        sObjectField16.setPermissionable(true);
        sObjectField16.setCascadeDelete(false);
        sObjectField16.setDefaultedOnCreate(false);
        sObjectField16.setExternalId(false);
        sObjectField16.setSoapType("xsd:string");
        sObjectField16.setScale(0);
        sObjectField16.setCustom(false);
        sObjectField16.setGroupable(true);
        sObjectField16.setRestrictedDelete(false);
        sObjectField16.setCalculated(false);
        sObjectField16.setNamePointing(false);
        sObjectField16.setIdLookup(false);
        sObjectField16.setType("string");
        sObjectField16.setPrecision(0);
        sObjectField16.setLength(255);
        sObjectField16.setSortable(true);
        sObjectField16.setByteLength(765);
        sObjectField16.setUpdateable(true);
        sObjectField16.setFilterable(true);
        sObjectField16.setQueryByDistance(false);
        sObjectField16.setUnique(false);
        sObjectField16.setAutoNumber(false);

        final SObjectField sObjectField17 = new SObjectField();
        fields1.add(sObjectField17);

        sObjectField17.setWriteRequiresMasterRead(false);
        sObjectField17.setNillable(true);
        sObjectField17.setCreateable(true);
        sObjectField17.setEncrypted(false);
        sObjectField17.setDependentPicklist(false);
        sObjectField17.setDigits("0");
        sObjectField17.setLabel("Priority");
        sObjectField17.setHighScaleNumber(false);
        sObjectField17.setDisplayLocationInDecimal(false);
        sObjectField17.setName("Priority");
        sObjectField17.setHtmlFormatted(false);
        sObjectField17.setDeprecatedAndHidden(false);
        sObjectField17.setDefaultValue("Medium");
        sObjectField17.setRestrictedPicklist(false);
        sObjectField17.setNameField(false);
        sObjectField17.setCaseSensitive(false);
        sObjectField17.setPermissionable(true);
        sObjectField17.setCascadeDelete(false);
        sObjectField17.setDefaultedOnCreate(true);
        sObjectField17.setExternalId(false);
        sObjectField17.setSoapType("xsd:string");
        sObjectField17.setScale(0);
        sObjectField17.setCustom(false);
        sObjectField17.setGroupable(true);
        sObjectField17.setRestrictedDelete(false);
        sObjectField17.setCalculated(false);
        sObjectField17.setNamePointing(false);
        sObjectField17.setIdLookup(false);
        sObjectField17.setType("picklist");
        sObjectField17.setPrecision(0);
        sObjectField17.setLength(40);
        sObjectField17.setSortable(true);
        sObjectField17.setByteLength(120);
        sObjectField17.setUpdateable(true);
        sObjectField17.setFilterable(true);
        sObjectField17.setQueryByDistance(false);
        sObjectField17.setUnique(false);
        sObjectField17.setAutoNumber(false);

        final SObjectField sObjectField18 = new SObjectField();
        fields1.add(sObjectField18);

        sObjectField18.setWriteRequiresMasterRead(false);
        sObjectField18.setNillable(true);
        sObjectField18.setCreateable(true);
        sObjectField18.setEncrypted(false);
        sObjectField18.setDependentPicklist(false);
        sObjectField18.setExtraTypeInfo("plaintextarea");
        sObjectField18.setDigits("0");
        sObjectField18.setLabel("Description");
        sObjectField18.setHighScaleNumber(false);
        sObjectField18.setDisplayLocationInDecimal(false);
        sObjectField18.setName("Description");
        sObjectField18.setHtmlFormatted(false);
        sObjectField18.setDeprecatedAndHidden(false);
        sObjectField18.setRestrictedPicklist(false);
        sObjectField18.setNameField(false);
        sObjectField18.setCaseSensitive(false);
        sObjectField18.setPermissionable(true);
        sObjectField18.setCascadeDelete(false);
        sObjectField18.setDefaultedOnCreate(false);
        sObjectField18.setExternalId(false);
        sObjectField18.setSoapType("xsd:string");
        sObjectField18.setScale(0);
        sObjectField18.setCustom(false);
        sObjectField18.setGroupable(false);
        sObjectField18.setRestrictedDelete(false);
        sObjectField18.setCalculated(false);
        sObjectField18.setNamePointing(false);
        sObjectField18.setIdLookup(false);
        sObjectField18.setType("textarea");
        sObjectField18.setPrecision(0);
        sObjectField18.setLength(32000);
        sObjectField18.setSortable(false);
        sObjectField18.setByteLength(96000);
        sObjectField18.setUpdateable(true);
        sObjectField18.setFilterable(false);
        sObjectField18.setQueryByDistance(false);
        sObjectField18.setUnique(false);
        sObjectField18.setAutoNumber(false);

        final SObjectField sObjectField19 = new SObjectField();
        fields1.add(sObjectField19);

        sObjectField19.setWriteRequiresMasterRead(false);
        sObjectField19.setNillable(false);
        sObjectField19.setCreateable(false);
        sObjectField19.setEncrypted(false);
        sObjectField19.setDependentPicklist(false);
        sObjectField19.setDigits("0");
        sObjectField19.setLabel("Closed");
        sObjectField19.setHighScaleNumber(false);
        sObjectField19.setDisplayLocationInDecimal(false);
        sObjectField19.setName("IsClosed");
        sObjectField19.setHtmlFormatted(false);
        sObjectField19.setDeprecatedAndHidden(false);
        sObjectField19.setDefaultValue("false");
        sObjectField19.setRestrictedPicklist(false);
        sObjectField19.setNameField(false);
        sObjectField19.setCaseSensitive(false);
        sObjectField19.setPermissionable(false);
        sObjectField19.setCascadeDelete(false);
        sObjectField19.setDefaultedOnCreate(true);
        sObjectField19.setExternalId(false);
        sObjectField19.setSoapType("xsd:boolean");
        sObjectField19.setScale(0);
        sObjectField19.setCustom(false);
        sObjectField19.setGroupable(true);
        sObjectField19.setRestrictedDelete(false);
        sObjectField19.setCalculated(false);
        sObjectField19.setNamePointing(false);
        sObjectField19.setIdLookup(false);
        sObjectField19.setType("boolean");
        sObjectField19.setPrecision(0);
        sObjectField19.setLength(0);
        sObjectField19.setSortable(true);
        sObjectField19.setByteLength(0);
        sObjectField19.setUpdateable(false);
        sObjectField19.setFilterable(true);
        sObjectField19.setQueryByDistance(false);
        sObjectField19.setUnique(false);
        sObjectField19.setAutoNumber(false);

        final SObjectField sObjectField20 = new SObjectField();
        fields1.add(sObjectField20);

        sObjectField20.setWriteRequiresMasterRead(false);
        sObjectField20.setNillable(true);
        sObjectField20.setCreateable(false);
        sObjectField20.setEncrypted(false);
        sObjectField20.setDependentPicklist(false);
        sObjectField20.setDigits("0");
        sObjectField20.setLabel("Closed Date");
        sObjectField20.setHighScaleNumber(false);
        sObjectField20.setDisplayLocationInDecimal(false);
        sObjectField20.setName("ClosedDate");
        sObjectField20.setHtmlFormatted(false);
        sObjectField20.setDeprecatedAndHidden(false);
        sObjectField20.setRestrictedPicklist(false);
        sObjectField20.setNameField(false);
        sObjectField20.setCaseSensitive(false);
        sObjectField20.setPermissionable(true);
        sObjectField20.setCascadeDelete(false);
        sObjectField20.setDefaultedOnCreate(false);
        sObjectField20.setExternalId(false);
        sObjectField20.setSoapType("xsd:dateTime");
        sObjectField20.setScale(0);
        sObjectField20.setCustom(false);
        sObjectField20.setGroupable(false);
        sObjectField20.setRestrictedDelete(false);
        sObjectField20.setCalculated(false);
        sObjectField20.setNamePointing(false);
        sObjectField20.setIdLookup(false);
        sObjectField20.setType("datetime");
        sObjectField20.setPrecision(0);
        sObjectField20.setLength(0);
        sObjectField20.setSortable(true);
        sObjectField20.setByteLength(0);
        sObjectField20.setUpdateable(false);
        sObjectField20.setFilterable(true);
        sObjectField20.setQueryByDistance(false);
        sObjectField20.setUnique(false);
        sObjectField20.setAutoNumber(false);

        final SObjectField sObjectField21 = new SObjectField();
        fields1.add(sObjectField21);

        sObjectField21.setWriteRequiresMasterRead(false);
        sObjectField21.setNillable(false);
        sObjectField21.setCreateable(true);
        sObjectField21.setEncrypted(false);
        sObjectField21.setDependentPicklist(false);
        sObjectField21.setDigits("0");
        sObjectField21.setLabel("Escalated");
        sObjectField21.setHighScaleNumber(false);
        sObjectField21.setDisplayLocationInDecimal(false);
        sObjectField21.setName("IsEscalated");
        sObjectField21.setHtmlFormatted(false);
        sObjectField21.setDeprecatedAndHidden(false);
        sObjectField21.setDefaultValue("false");
        sObjectField21.setRestrictedPicklist(false);
        sObjectField21.setNameField(false);
        sObjectField21.setCaseSensitive(false);
        sObjectField21.setPermissionable(true);
        sObjectField21.setCascadeDelete(false);
        sObjectField21.setDefaultedOnCreate(true);
        sObjectField21.setExternalId(false);
        sObjectField21.setSoapType("xsd:boolean");
        sObjectField21.setScale(0);
        sObjectField21.setCustom(false);
        sObjectField21.setGroupable(true);
        sObjectField21.setRestrictedDelete(false);
        sObjectField21.setCalculated(false);
        sObjectField21.setNamePointing(false);
        sObjectField21.setIdLookup(false);
        sObjectField21.setType("boolean");
        sObjectField21.setPrecision(0);
        sObjectField21.setLength(0);
        sObjectField21.setSortable(true);
        sObjectField21.setByteLength(0);
        sObjectField21.setUpdateable(true);
        sObjectField21.setFilterable(true);
        sObjectField21.setQueryByDistance(false);
        sObjectField21.setUnique(false);
        sObjectField21.setAutoNumber(false);

        final SObjectField sObjectField22 = new SObjectField();
        fields1.add(sObjectField22);

        sObjectField22.setWriteRequiresMasterRead(false);
        sObjectField22.setNillable(false);
        sObjectField22.setCreateable(true);
        sObjectField22.setEncrypted(false);
        sObjectField22.setDependentPicklist(false);
        sObjectField22.setDigits("0");
        sObjectField22.setLabel("Owner ID");
        sObjectField22.setHighScaleNumber(false);
        sObjectField22.setDisplayLocationInDecimal(false);
        sObjectField22.setName("OwnerId");
        sObjectField22.setHtmlFormatted(false);
        sObjectField22.setDeprecatedAndHidden(false);
        sObjectField22.setRestrictedPicklist(false);
        sObjectField22.setNameField(false);
        sObjectField22.setCaseSensitive(false);
        sObjectField22.setPermissionable(false);
        sObjectField22.setCascadeDelete(false);
        sObjectField22.setDefaultedOnCreate(true);
        sObjectField22.setExternalId(false);
        sObjectField22.setSoapType("tns:ID");
        sObjectField22.setScale(0);
        sObjectField22.setCustom(false);
        sObjectField22.setGroupable(true);
        sObjectField22.setRestrictedDelete(false);
        sObjectField22.setCalculated(false);
        sObjectField22.setNamePointing(true);
        sObjectField22.setIdLookup(false);
        sObjectField22.setType("reference");
        sObjectField22.setRelationshipName("Owner");

        final List<String> referenceTo5 = new ArrayList<>();
        sObjectField22.setReferenceTo(referenceTo5);

        referenceTo5.add("Group");
        referenceTo5.add("User");

        sObjectField22.setPrecision(0);
        sObjectField22.setLength(18);
        sObjectField22.setSortable(true);
        sObjectField22.setByteLength(18);
        sObjectField22.setUpdateable(true);
        sObjectField22.setFilterable(true);
        sObjectField22.setQueryByDistance(false);
        sObjectField22.setUnique(false);
        sObjectField22.setAutoNumber(false);

        final SObjectField sObjectField23 = new SObjectField();
        fields1.add(sObjectField23);

        sObjectField23.setWriteRequiresMasterRead(false);
        sObjectField23.setNillable(false);
        sObjectField23.setCreateable(false);
        sObjectField23.setEncrypted(false);
        sObjectField23.setDependentPicklist(false);
        sObjectField23.setDigits("0");
        sObjectField23.setLabel("Created Date");
        sObjectField23.setHighScaleNumber(false);
        sObjectField23.setDisplayLocationInDecimal(false);
        sObjectField23.setName("CreatedDate");
        sObjectField23.setHtmlFormatted(false);
        sObjectField23.setDeprecatedAndHidden(false);
        sObjectField23.setRestrictedPicklist(false);
        sObjectField23.setNameField(false);
        sObjectField23.setCaseSensitive(false);
        sObjectField23.setPermissionable(false);
        sObjectField23.setCascadeDelete(false);
        sObjectField23.setDefaultedOnCreate(true);
        sObjectField23.setExternalId(false);
        sObjectField23.setSoapType("xsd:dateTime");
        sObjectField23.setScale(0);
        sObjectField23.setCustom(false);
        sObjectField23.setGroupable(false);
        sObjectField23.setRestrictedDelete(false);
        sObjectField23.setCalculated(false);
        sObjectField23.setNamePointing(false);
        sObjectField23.setIdLookup(false);
        sObjectField23.setType("datetime");
        sObjectField23.setPrecision(0);
        sObjectField23.setLength(0);
        sObjectField23.setSortable(true);
        sObjectField23.setByteLength(0);
        sObjectField23.setUpdateable(false);
        sObjectField23.setFilterable(true);
        sObjectField23.setQueryByDistance(false);
        sObjectField23.setUnique(false);
        sObjectField23.setAutoNumber(false);

        final SObjectField sObjectField24 = new SObjectField();
        fields1.add(sObjectField24);

        sObjectField24.setWriteRequiresMasterRead(false);
        sObjectField24.setNillable(false);
        sObjectField24.setCreateable(false);
        sObjectField24.setEncrypted(false);
        sObjectField24.setDependentPicklist(false);
        sObjectField24.setDigits("0");
        sObjectField24.setLabel("Created By ID");
        sObjectField24.setHighScaleNumber(false);
        sObjectField24.setDisplayLocationInDecimal(false);
        sObjectField24.setName("CreatedById");
        sObjectField24.setHtmlFormatted(false);
        sObjectField24.setDeprecatedAndHidden(false);
        sObjectField24.setRestrictedPicklist(false);
        sObjectField24.setNameField(false);
        sObjectField24.setCaseSensitive(false);
        sObjectField24.setPermissionable(false);
        sObjectField24.setCascadeDelete(false);
        sObjectField24.setDefaultedOnCreate(true);
        sObjectField24.setExternalId(false);
        sObjectField24.setSoapType("tns:ID");
        sObjectField24.setScale(0);
        sObjectField24.setCustom(false);
        sObjectField24.setGroupable(true);
        sObjectField24.setRestrictedDelete(false);
        sObjectField24.setCalculated(false);
        sObjectField24.setNamePointing(false);
        sObjectField24.setIdLookup(false);
        sObjectField24.setType("reference");
        sObjectField24.setRelationshipName("CreatedBy");

        final List<String> referenceTo6 = new ArrayList<>();
        sObjectField24.setReferenceTo(referenceTo6);

        referenceTo6.add("User");

        sObjectField24.setPrecision(0);
        sObjectField24.setLength(18);
        sObjectField24.setSortable(true);
        sObjectField24.setByteLength(18);
        sObjectField24.setUpdateable(false);
        sObjectField24.setFilterable(true);
        sObjectField24.setQueryByDistance(false);
        sObjectField24.setUnique(false);
        sObjectField24.setAutoNumber(false);

        final SObjectField sObjectField25 = new SObjectField();
        fields1.add(sObjectField25);

        sObjectField25.setWriteRequiresMasterRead(false);
        sObjectField25.setNillable(false);
        sObjectField25.setCreateable(false);
        sObjectField25.setEncrypted(false);
        sObjectField25.setDependentPicklist(false);
        sObjectField25.setDigits("0");
        sObjectField25.setLabel("Last Modified Date");
        sObjectField25.setHighScaleNumber(false);
        sObjectField25.setDisplayLocationInDecimal(false);
        sObjectField25.setName("LastModifiedDate");
        sObjectField25.setHtmlFormatted(false);
        sObjectField25.setDeprecatedAndHidden(false);
        sObjectField25.setRestrictedPicklist(false);
        sObjectField25.setNameField(false);
        sObjectField25.setCaseSensitive(false);
        sObjectField25.setPermissionable(false);
        sObjectField25.setCascadeDelete(false);
        sObjectField25.setDefaultedOnCreate(true);
        sObjectField25.setExternalId(false);
        sObjectField25.setSoapType("xsd:dateTime");
        sObjectField25.setScale(0);
        sObjectField25.setCustom(false);
        sObjectField25.setGroupable(false);
        sObjectField25.setRestrictedDelete(false);
        sObjectField25.setCalculated(false);
        sObjectField25.setNamePointing(false);
        sObjectField25.setIdLookup(false);
        sObjectField25.setType("datetime");
        sObjectField25.setPrecision(0);
        sObjectField25.setLength(0);
        sObjectField25.setSortable(true);
        sObjectField25.setByteLength(0);
        sObjectField25.setUpdateable(false);
        sObjectField25.setFilterable(true);
        sObjectField25.setQueryByDistance(false);
        sObjectField25.setUnique(false);
        sObjectField25.setAutoNumber(false);

        final SObjectField sObjectField26 = new SObjectField();
        fields1.add(sObjectField26);

        sObjectField26.setWriteRequiresMasterRead(false);
        sObjectField26.setNillable(false);
        sObjectField26.setCreateable(false);
        sObjectField26.setEncrypted(false);
        sObjectField26.setDependentPicklist(false);
        sObjectField26.setDigits("0");
        sObjectField26.setLabel("Last Modified By ID");
        sObjectField26.setHighScaleNumber(false);
        sObjectField26.setDisplayLocationInDecimal(false);
        sObjectField26.setName("LastModifiedById");
        sObjectField26.setHtmlFormatted(false);
        sObjectField26.setDeprecatedAndHidden(false);
        sObjectField26.setRestrictedPicklist(false);
        sObjectField26.setNameField(false);
        sObjectField26.setCaseSensitive(false);
        sObjectField26.setPermissionable(false);
        sObjectField26.setCascadeDelete(false);
        sObjectField26.setDefaultedOnCreate(true);
        sObjectField26.setExternalId(false);
        sObjectField26.setSoapType("tns:ID");
        sObjectField26.setScale(0);
        sObjectField26.setCustom(false);
        sObjectField26.setGroupable(true);
        sObjectField26.setRestrictedDelete(false);
        sObjectField26.setCalculated(false);
        sObjectField26.setNamePointing(false);
        sObjectField26.setIdLookup(false);
        sObjectField26.setType("reference");
        sObjectField26.setRelationshipName("LastModifiedBy");

        final List<String> referenceTo7 = new ArrayList<>();
        sObjectField26.setReferenceTo(referenceTo7);

        referenceTo7.add("User");

        sObjectField26.setPrecision(0);
        sObjectField26.setLength(18);
        sObjectField26.setSortable(true);
        sObjectField26.setByteLength(18);
        sObjectField26.setUpdateable(false);
        sObjectField26.setFilterable(true);
        sObjectField26.setQueryByDistance(false);
        sObjectField26.setUnique(false);
        sObjectField26.setAutoNumber(false);

        final SObjectField sObjectField27 = new SObjectField();
        fields1.add(sObjectField27);

        sObjectField27.setWriteRequiresMasterRead(false);
        sObjectField27.setNillable(false);
        sObjectField27.setCreateable(false);
        sObjectField27.setEncrypted(false);
        sObjectField27.setDependentPicklist(false);
        sObjectField27.setDigits("0");
        sObjectField27.setLabel("System Modstamp");
        sObjectField27.setHighScaleNumber(false);
        sObjectField27.setDisplayLocationInDecimal(false);
        sObjectField27.setName("SystemModstamp");
        sObjectField27.setHtmlFormatted(false);
        sObjectField27.setDeprecatedAndHidden(false);
        sObjectField27.setRestrictedPicklist(false);
        sObjectField27.setNameField(false);
        sObjectField27.setCaseSensitive(false);
        sObjectField27.setPermissionable(false);
        sObjectField27.setCascadeDelete(false);
        sObjectField27.setDefaultedOnCreate(true);
        sObjectField27.setExternalId(false);
        sObjectField27.setSoapType("xsd:dateTime");
        sObjectField27.setScale(0);
        sObjectField27.setCustom(false);
        sObjectField27.setGroupable(false);
        sObjectField27.setRestrictedDelete(false);
        sObjectField27.setCalculated(false);
        sObjectField27.setNamePointing(false);
        sObjectField27.setIdLookup(false);
        sObjectField27.setType("datetime");
        sObjectField27.setPrecision(0);
        sObjectField27.setLength(0);
        sObjectField27.setSortable(true);
        sObjectField27.setByteLength(0);
        sObjectField27.setUpdateable(false);
        sObjectField27.setFilterable(true);
        sObjectField27.setQueryByDistance(false);
        sObjectField27.setUnique(false);
        sObjectField27.setAutoNumber(false);

        final SObjectField sObjectField28 = new SObjectField();
        fields1.add(sObjectField28);

        sObjectField28.setWriteRequiresMasterRead(false);
        sObjectField28.setNillable(true);
        sObjectField28.setCreateable(false);
        sObjectField28.setEncrypted(false);
        sObjectField28.setDependentPicklist(false);
        sObjectField28.setDigits("0");
        sObjectField28.setLabel("Contact Phone");
        sObjectField28.setHighScaleNumber(false);
        sObjectField28.setDisplayLocationInDecimal(false);
        sObjectField28.setName("ContactPhone");
        sObjectField28.setHtmlFormatted(false);
        sObjectField28.setDeprecatedAndHidden(false);
        sObjectField28.setRestrictedPicklist(false);
        sObjectField28.setNameField(false);
        sObjectField28.setCaseSensitive(false);
        sObjectField28.setPermissionable(false);
        sObjectField28.setCascadeDelete(false);
        sObjectField28.setDefaultedOnCreate(false);
        sObjectField28.setExternalId(false);
        sObjectField28.setSoapType("xsd:string");
        sObjectField28.setScale(0);
        sObjectField28.setCustom(false);
        sObjectField28.setGroupable(true);
        sObjectField28.setRestrictedDelete(false);
        sObjectField28.setCalculated(false);
        sObjectField28.setNamePointing(false);
        sObjectField28.setIdLookup(false);
        sObjectField28.setType("phone");
        sObjectField28.setPrecision(0);
        sObjectField28.setLength(40);
        sObjectField28.setSortable(true);
        sObjectField28.setByteLength(120);
        sObjectField28.setUpdateable(false);
        sObjectField28.setFilterable(true);
        sObjectField28.setQueryByDistance(false);
        sObjectField28.setUnique(false);
        sObjectField28.setAutoNumber(false);

        final SObjectField sObjectField29 = new SObjectField();
        fields1.add(sObjectField29);

        sObjectField29.setWriteRequiresMasterRead(false);
        sObjectField29.setNillable(true);
        sObjectField29.setCreateable(false);
        sObjectField29.setEncrypted(false);
        sObjectField29.setDependentPicklist(false);
        sObjectField29.setDigits("0");
        sObjectField29.setLabel("Contact Mobile");
        sObjectField29.setHighScaleNumber(false);
        sObjectField29.setDisplayLocationInDecimal(false);
        sObjectField29.setName("ContactMobile");
        sObjectField29.setHtmlFormatted(false);
        sObjectField29.setDeprecatedAndHidden(false);
        sObjectField29.setRestrictedPicklist(false);
        sObjectField29.setNameField(false);
        sObjectField29.setCaseSensitive(false);
        sObjectField29.setPermissionable(false);
        sObjectField29.setCascadeDelete(false);
        sObjectField29.setDefaultedOnCreate(false);
        sObjectField29.setExternalId(false);
        sObjectField29.setSoapType("xsd:string");
        sObjectField29.setScale(0);
        sObjectField29.setCustom(false);
        sObjectField29.setGroupable(true);
        sObjectField29.setRestrictedDelete(false);
        sObjectField29.setCalculated(false);
        sObjectField29.setNamePointing(false);
        sObjectField29.setIdLookup(false);
        sObjectField29.setType("phone");
        sObjectField29.setPrecision(0);
        sObjectField29.setLength(40);
        sObjectField29.setSortable(true);
        sObjectField29.setByteLength(120);
        sObjectField29.setUpdateable(false);
        sObjectField29.setFilterable(true);
        sObjectField29.setQueryByDistance(false);
        sObjectField29.setUnique(false);
        sObjectField29.setAutoNumber(false);

        final SObjectField sObjectField30 = new SObjectField();
        fields1.add(sObjectField30);

        sObjectField30.setWriteRequiresMasterRead(false);
        sObjectField30.setNillable(true);
        sObjectField30.setCreateable(false);
        sObjectField30.setEncrypted(false);
        sObjectField30.setDependentPicklist(false);
        sObjectField30.setDigits("0");
        sObjectField30.setLabel("Contact Email");
        sObjectField30.setHighScaleNumber(false);
        sObjectField30.setDisplayLocationInDecimal(false);
        sObjectField30.setName("ContactEmail");
        sObjectField30.setHtmlFormatted(false);
        sObjectField30.setDeprecatedAndHidden(false);
        sObjectField30.setRestrictedPicklist(false);
        sObjectField30.setNameField(false);
        sObjectField30.setCaseSensitive(false);
        sObjectField30.setPermissionable(false);
        sObjectField30.setCascadeDelete(false);
        sObjectField30.setDefaultedOnCreate(false);
        sObjectField30.setExternalId(false);
        sObjectField30.setSoapType("xsd:string");
        sObjectField30.setScale(0);
        sObjectField30.setCustom(false);
        sObjectField30.setGroupable(true);
        sObjectField30.setRestrictedDelete(false);
        sObjectField30.setCalculated(false);
        sObjectField30.setNamePointing(false);
        sObjectField30.setIdLookup(false);
        sObjectField30.setType("email");
        sObjectField30.setPrecision(0);
        sObjectField30.setLength(80);
        sObjectField30.setSortable(true);
        sObjectField30.setByteLength(240);
        sObjectField30.setUpdateable(false);
        sObjectField30.setFilterable(true);
        sObjectField30.setQueryByDistance(false);
        sObjectField30.setUnique(false);
        sObjectField30.setAutoNumber(false);

        final SObjectField sObjectField31 = new SObjectField();
        fields1.add(sObjectField31);

        sObjectField31.setWriteRequiresMasterRead(false);
        sObjectField31.setNillable(true);
        sObjectField31.setCreateable(false);
        sObjectField31.setEncrypted(false);
        sObjectField31.setDependentPicklist(false);
        sObjectField31.setDigits("0");
        sObjectField31.setLabel("Contact Fax");
        sObjectField31.setHighScaleNumber(false);
        sObjectField31.setDisplayLocationInDecimal(false);
        sObjectField31.setName("ContactFax");
        sObjectField31.setHtmlFormatted(false);
        sObjectField31.setDeprecatedAndHidden(false);
        sObjectField31.setRestrictedPicklist(false);
        sObjectField31.setNameField(false);
        sObjectField31.setCaseSensitive(false);
        sObjectField31.setPermissionable(false);
        sObjectField31.setCascadeDelete(false);
        sObjectField31.setDefaultedOnCreate(false);
        sObjectField31.setExternalId(false);
        sObjectField31.setSoapType("xsd:string");
        sObjectField31.setScale(0);
        sObjectField31.setCustom(false);
        sObjectField31.setGroupable(true);
        sObjectField31.setRestrictedDelete(false);
        sObjectField31.setCalculated(false);
        sObjectField31.setNamePointing(false);
        sObjectField31.setIdLookup(false);
        sObjectField31.setType("phone");
        sObjectField31.setPrecision(0);
        sObjectField31.setLength(40);
        sObjectField31.setSortable(true);
        sObjectField31.setByteLength(120);
        sObjectField31.setUpdateable(false);
        sObjectField31.setFilterable(true);
        sObjectField31.setQueryByDistance(false);
        sObjectField31.setUnique(false);
        sObjectField31.setAutoNumber(false);

        final SObjectField sObjectField32 = new SObjectField();
        fields1.add(sObjectField32);

        sObjectField32.setWriteRequiresMasterRead(false);
        sObjectField32.setNillable(true);
        sObjectField32.setCreateable(false);
        sObjectField32.setEncrypted(false);
        sObjectField32.setDependentPicklist(false);
        sObjectField32.setDigits("0");
        sObjectField32.setLabel("Last Viewed Date");
        sObjectField32.setHighScaleNumber(false);
        sObjectField32.setDisplayLocationInDecimal(false);
        sObjectField32.setName("LastViewedDate");
        sObjectField32.setHtmlFormatted(false);
        sObjectField32.setDeprecatedAndHidden(false);
        sObjectField32.setRestrictedPicklist(false);
        sObjectField32.setNameField(false);
        sObjectField32.setCaseSensitive(false);
        sObjectField32.setPermissionable(false);
        sObjectField32.setCascadeDelete(false);
        sObjectField32.setDefaultedOnCreate(false);
        sObjectField32.setExternalId(false);
        sObjectField32.setSoapType("xsd:dateTime");
        sObjectField32.setScale(0);
        sObjectField32.setCustom(false);
        sObjectField32.setGroupable(false);
        sObjectField32.setRestrictedDelete(false);
        sObjectField32.setCalculated(false);
        sObjectField32.setNamePointing(false);
        sObjectField32.setIdLookup(false);
        sObjectField32.setType("datetime");
        sObjectField32.setPrecision(0);
        sObjectField32.setLength(0);
        sObjectField32.setSortable(true);
        sObjectField32.setByteLength(0);
        sObjectField32.setUpdateable(false);
        sObjectField32.setFilterable(true);
        sObjectField32.setQueryByDistance(false);
        sObjectField32.setUnique(false);
        sObjectField32.setAutoNumber(false);

        final SObjectField sObjectField33 = new SObjectField();
        fields1.add(sObjectField33);

        sObjectField33.setWriteRequiresMasterRead(false);
        sObjectField33.setNillable(true);
        sObjectField33.setCreateable(false);
        sObjectField33.setEncrypted(false);
        sObjectField33.setDependentPicklist(false);
        sObjectField33.setDigits("0");
        sObjectField33.setLabel("Last Referenced Date");
        sObjectField33.setHighScaleNumber(false);
        sObjectField33.setDisplayLocationInDecimal(false);
        sObjectField33.setName("LastReferencedDate");
        sObjectField33.setHtmlFormatted(false);
        sObjectField33.setDeprecatedAndHidden(false);
        sObjectField33.setRestrictedPicklist(false);
        sObjectField33.setNameField(false);
        sObjectField33.setCaseSensitive(false);
        sObjectField33.setPermissionable(false);
        sObjectField33.setCascadeDelete(false);
        sObjectField33.setDefaultedOnCreate(false);
        sObjectField33.setExternalId(false);
        sObjectField33.setSoapType("xsd:dateTime");
        sObjectField33.setScale(0);
        sObjectField33.setCustom(false);
        sObjectField33.setGroupable(false);
        sObjectField33.setRestrictedDelete(false);
        sObjectField33.setCalculated(false);
        sObjectField33.setNamePointing(false);
        sObjectField33.setIdLookup(false);
        sObjectField33.setType("datetime");
        sObjectField33.setPrecision(0);
        sObjectField33.setLength(0);
        sObjectField33.setSortable(true);
        sObjectField33.setByteLength(0);
        sObjectField33.setUpdateable(false);
        sObjectField33.setFilterable(true);
        sObjectField33.setQueryByDistance(false);
        sObjectField33.setUnique(false);
        sObjectField33.setAutoNumber(false);

        final SObjectField sObjectField34 = new SObjectField();
        fields1.add(sObjectField34);

        sObjectField34.setWriteRequiresMasterRead(false);
        sObjectField34.setNillable(true);
        sObjectField34.setCreateable(true);
        sObjectField34.setEncrypted(false);
        sObjectField34.setDependentPicklist(false);
        sObjectField34.setDigits("0");
        sObjectField34.setLabel("Engineering Req Number");
        sObjectField34.setHighScaleNumber(false);
        sObjectField34.setDisplayLocationInDecimal(false);
        sObjectField34.setName("EngineeringReqNumber__c");
        sObjectField34.setHtmlFormatted(false);
        sObjectField34.setDeprecatedAndHidden(false);
        sObjectField34.setRestrictedPicklist(false);
        sObjectField34.setNameField(false);
        sObjectField34.setCaseSensitive(false);
        sObjectField34.setPermissionable(true);
        sObjectField34.setCascadeDelete(false);
        sObjectField34.setDefaultedOnCreate(false);
        sObjectField34.setExternalId(false);
        sObjectField34.setSoapType("xsd:string");
        sObjectField34.setScale(0);
        sObjectField34.setCustom(true);
        sObjectField34.setGroupable(true);
        sObjectField34.setRestrictedDelete(false);
        sObjectField34.setCalculated(false);
        sObjectField34.setNamePointing(false);
        sObjectField34.setIdLookup(false);
        sObjectField34.setType("string");
        sObjectField34.setPrecision(0);
        sObjectField34.setLength(12);
        sObjectField34.setSortable(true);
        sObjectField34.setByteLength(36);
        sObjectField34.setUpdateable(true);
        sObjectField34.setFilterable(true);
        sObjectField34.setQueryByDistance(false);
        sObjectField34.setUnique(false);
        sObjectField34.setAutoNumber(false);

        final SObjectField sObjectField35 = new SObjectField();
        fields1.add(sObjectField35);

        sObjectField35.setWriteRequiresMasterRead(false);
        sObjectField35.setNillable(true);
        sObjectField35.setCreateable(true);
        sObjectField35.setEncrypted(false);
        sObjectField35.setDependentPicklist(false);
        sObjectField35.setDigits("0");
        sObjectField35.setLabel("SLA Violation");
        sObjectField35.setHighScaleNumber(false);
        sObjectField35.setDisplayLocationInDecimal(false);
        sObjectField35.setName("SLAViolation__c");
        sObjectField35.setHtmlFormatted(false);
        sObjectField35.setDeprecatedAndHidden(false);
        sObjectField35.setRestrictedPicklist(false);
        sObjectField35.setNameField(false);
        sObjectField35.setCaseSensitive(false);
        sObjectField35.setPermissionable(true);
        sObjectField35.setCascadeDelete(false);
        sObjectField35.setDefaultedOnCreate(false);
        sObjectField35.setExternalId(false);
        sObjectField35.setSoapType("xsd:string");
        sObjectField35.setScale(0);
        sObjectField35.setCustom(true);
        sObjectField35.setGroupable(true);
        sObjectField35.setRestrictedDelete(false);
        sObjectField35.setCalculated(false);
        sObjectField35.setNamePointing(false);
        sObjectField35.setIdLookup(false);
        sObjectField35.setType("picklist");
        sObjectField35.setPrecision(0);
        sObjectField35.setLength(255);
        sObjectField35.setSortable(true);
        sObjectField35.setByteLength(765);
        sObjectField35.setUpdateable(true);
        sObjectField35.setFilterable(true);
        sObjectField35.setQueryByDistance(false);
        sObjectField35.setUnique(false);
        sObjectField35.setAutoNumber(false);

        final SObjectField sObjectField36 = new SObjectField();
        fields1.add(sObjectField36);

        sObjectField36.setWriteRequiresMasterRead(false);
        sObjectField36.setNillable(true);
        sObjectField36.setCreateable(true);
        sObjectField36.setEncrypted(false);
        sObjectField36.setDependentPicklist(false);
        sObjectField36.setDigits("0");
        sObjectField36.setLabel("Product");
        sObjectField36.setHighScaleNumber(false);
        sObjectField36.setDisplayLocationInDecimal(false);
        sObjectField36.setName("Product__c");
        sObjectField36.setHtmlFormatted(false);
        sObjectField36.setDeprecatedAndHidden(false);
        sObjectField36.setRestrictedPicklist(false);
        sObjectField36.setNameField(false);
        sObjectField36.setCaseSensitive(false);
        sObjectField36.setPermissionable(true);
        sObjectField36.setCascadeDelete(false);
        sObjectField36.setDefaultedOnCreate(false);
        sObjectField36.setExternalId(false);
        sObjectField36.setSoapType("xsd:string");
        sObjectField36.setScale(0);
        sObjectField36.setCustom(true);
        sObjectField36.setGroupable(true);
        sObjectField36.setRestrictedDelete(false);
        sObjectField36.setCalculated(false);
        sObjectField36.setNamePointing(false);
        sObjectField36.setIdLookup(false);
        sObjectField36.setType("picklist");
        sObjectField36.setPrecision(0);
        sObjectField36.setLength(255);
        sObjectField36.setSortable(true);
        sObjectField36.setByteLength(765);
        sObjectField36.setUpdateable(true);
        sObjectField36.setFilterable(true);
        sObjectField36.setQueryByDistance(false);
        sObjectField36.setUnique(false);
        sObjectField36.setAutoNumber(false);

        final SObjectField sObjectField37 = new SObjectField();
        fields1.add(sObjectField37);

        sObjectField37.setWriteRequiresMasterRead(false);
        sObjectField37.setNillable(true);
        sObjectField37.setCreateable(true);
        sObjectField37.setEncrypted(false);
        sObjectField37.setDependentPicklist(false);
        sObjectField37.setDigits("0");
        sObjectField37.setLabel("Potential Liability");
        sObjectField37.setHighScaleNumber(false);
        sObjectField37.setDisplayLocationInDecimal(false);
        sObjectField37.setName("PotentialLiability__c");
        sObjectField37.setHtmlFormatted(false);
        sObjectField37.setDeprecatedAndHidden(false);
        sObjectField37.setRestrictedPicklist(false);
        sObjectField37.setNameField(false);
        sObjectField37.setCaseSensitive(false);
        sObjectField37.setPermissionable(true);
        sObjectField37.setCascadeDelete(false);
        sObjectField37.setDefaultedOnCreate(false);
        sObjectField37.setExternalId(false);
        sObjectField37.setSoapType("xsd:string");
        sObjectField37.setScale(0);
        sObjectField37.setCustom(true);
        sObjectField37.setGroupable(true);
        sObjectField37.setRestrictedDelete(false);
        sObjectField37.setCalculated(false);
        sObjectField37.setNamePointing(false);
        sObjectField37.setIdLookup(false);
        sObjectField37.setType("picklist");
        sObjectField37.setPrecision(0);
        sObjectField37.setLength(255);
        sObjectField37.setSortable(true);
        sObjectField37.setByteLength(765);
        sObjectField37.setUpdateable(true);
        sObjectField37.setFilterable(true);
        sObjectField37.setQueryByDistance(false);
        sObjectField37.setUnique(false);
        sObjectField37.setAutoNumber(false);

        final SObjectField sObjectField38 = new SObjectField();
        fields1.add(sObjectField38);

        sObjectField38.setWriteRequiresMasterRead(false);
        sObjectField38.setNillable(true);
        sObjectField38.setCreateable(true);
        sObjectField38.setEncrypted(false);
        sObjectField38.setDependentPicklist(false);
        sObjectField38.setDigits("0");
        sObjectField38.setLabel("ExtenralID");
        sObjectField38.setHighScaleNumber(false);
        sObjectField38.setDisplayLocationInDecimal(false);
        sObjectField38.setName("ExtenralID__c");
        sObjectField38.setHtmlFormatted(false);
        sObjectField38.setDeprecatedAndHidden(false);
        sObjectField38.setRestrictedPicklist(false);
        sObjectField38.setNameField(false);
        sObjectField38.setCaseSensitive(false);
        sObjectField38.setPermissionable(true);
        sObjectField38.setCascadeDelete(false);
        sObjectField38.setDefaultedOnCreate(false);
        sObjectField38.setExternalId(true);
        sObjectField38.setSoapType("xsd:string");
        sObjectField38.setScale(0);
        sObjectField38.setCustom(true);
        sObjectField38.setGroupable(true);
        sObjectField38.setRestrictedDelete(false);
        sObjectField38.setCalculated(false);
        sObjectField38.setNamePointing(false);
        sObjectField38.setIdLookup(true);
        sObjectField38.setType("string");
        sObjectField38.setPrecision(0);
        sObjectField38.setLength(128);
        sObjectField38.setSortable(true);
        sObjectField38.setByteLength(384);
        sObjectField38.setUpdateable(true);
        sObjectField38.setFilterable(true);
        sObjectField38.setQueryByDistance(false);
        sObjectField38.setUnique(false);
        sObjectField38.setAutoNumber(false);

        final SObjectField sObjectField39 = new SObjectField();
        fields1.add(sObjectField39);

        sObjectField39.setWriteRequiresMasterRead(false);
        sObjectField39.setNillable(true);
        sObjectField39.setCreateable(true);
        sObjectField39.setEncrypted(false);
        sObjectField39.setDependentPicklist(false);
        sObjectField39.setDigits("0");
        sObjectField39.setLabel("InternalID");
        sObjectField39.setHighScaleNumber(false);
        sObjectField39.setDisplayLocationInDecimal(false);
        sObjectField39.setName("InternalID__c");
        sObjectField39.setHtmlFormatted(false);
        sObjectField39.setDeprecatedAndHidden(false);
        sObjectField39.setRestrictedPicklist(false);
        sObjectField39.setNameField(false);
        sObjectField39.setCaseSensitive(false);
        sObjectField39.setPermissionable(true);
        sObjectField39.setCascadeDelete(false);
        sObjectField39.setDefaultedOnCreate(false);
        sObjectField39.setExternalId(false);
        sObjectField39.setSoapType("xsd:string");
        sObjectField39.setScale(0);
        sObjectField39.setCustom(true);
        sObjectField39.setGroupable(true);
        sObjectField39.setRestrictedDelete(false);
        sObjectField39.setCalculated(false);
        sObjectField39.setNamePointing(false);
        sObjectField39.setIdLookup(false);
        sObjectField39.setType("string");
        sObjectField39.setPrecision(0);
        sObjectField39.setLength(128);
        sObjectField39.setSortable(true);
        sObjectField39.setByteLength(384);
        sObjectField39.setUpdateable(true);
        sObjectField39.setFilterable(true);
        sObjectField39.setQueryByDistance(false);
        sObjectField39.setUnique(false);
        sObjectField39.setAutoNumber(false);


        description.setActivateable(false);
        description.setUpdateable(true);
        description.setLabelPlural("Cases");
        description.setDeletable(true);

        return description;
    }
}
