/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Nov 18 14:59:16 CET 2016
 */
package com.github.lburgazzoli.camel.salesforce.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist OtherGeocodeAccuracy
 */
public enum Contact_OtherGeocodeAccuracyEnum {

    // Address
    ADDRESS("Address"),
    // Block
    BLOCK("Block"),
    // City
    CITY("City"),
    // County
    COUNTY("County"),
    // ExtendedZip
    EXTENDEDZIP("ExtendedZip"),
    // NearAddress
    NEARADDRESS("NearAddress"),
    // Neighborhood
    NEIGHBORHOOD("Neighborhood"),
    // State
    STATE("State"),
    // Street
    STREET("Street"),
    // Unknown
    UNKNOWN("Unknown"),
    // Zip
    ZIP("Zip");

    final String value;

    private Contact_OtherGeocodeAccuracyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Contact_OtherGeocodeAccuracyEnum fromValue(String value) {
        for (Contact_OtherGeocodeAccuracyEnum e : Contact_OtherGeocodeAccuracyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
