/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Nov 18 14:59:16 CET 2016
 */
package com.github.lburgazzoli.camel.salesforce.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Level__c
 */
public enum Contact_LevelEnum {

    // Primary
    PRIMARY("Primary"),
    // Secondary
    SECONDARY("Secondary"),
    // Tertiary
    TERTIARY("Tertiary");

    final String value;

    private Contact_LevelEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Contact_LevelEnum fromValue(String value) {
        for (Contact_LevelEnum e : Contact_LevelEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
