/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 23 10:44:07 CEST 2017
 */
package com.github.lburgazzoli.camel.salesforce.model;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;

/**
 * Salesforce QueryRecords DTO for type CaseComment
 */
public class QueryRecordsCaseComment extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<CaseComment> records;

    public List<CaseComment> getRecords() {
        return records;
    }

    public void setRecords(List<CaseComment> records) {
        this.records = records;
    }
}
