/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Nov 07 14:32:02 CET 2016
 */
package com.github.lburgazzoli.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Origin
 */
public enum Case_OriginEnum {

    // Email
    EMAIL("Email"),
    // Phone
    PHONE("Phone"),
    // Web
    WEB("Web");

    final String value;

    private Case_OriginEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Case_OriginEnum fromValue(String value) {
        for (Case_OriginEnum e : Case_OriginEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
